#############################################################################
# Makefile for building: valkyrie
# Generated by qmake (3.0) (Qt 5.1.1) on: Thu Mar 29 21:07:12 2018
# Project:  valkyrie.pro
# Template: subdirs
# Command: /Users/prodesign/Qt5.1.1/5.1.1/clang_64/bin/qmake PREFIX=/usr/local -o Makefile valkyrie.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /Users/prodesign/Qt5.1.1/5.1.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-src


sub-src-qmake_all:  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: valkyrie.pro ../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf ../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf \
		vk_config.pri \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf \
		../Qt5.1.1/5.1.1/clang_64/mkspecs/features/silent.prf \
		valkyrie.pro
	$(QMAKE) PREFIX=/usr/local -o Makefile valkyrie.pro
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_pre.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/qdevice.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/device_config.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/shell-unix.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/unix.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/mac.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/macx.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/common/clang-mac.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/qconfig.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_clucene.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_designercomponents.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_platformsupport.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_quickparticles.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_v8.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_functions.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/qt_config.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/macx-clang/qmake.conf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/spec_post.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exclusive_builds.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_pre.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/unix/default_pre.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_pre.prf:
vk_config.pri:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/resolve_config.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/default_post.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/sdk.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/default_post.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/objective_c.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/warn_on.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/mac/rez.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/testcase_targets.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/exceptions.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/yacc.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/lex.prf:
../Qt5.1.1/5.1.1/clang_64/mkspecs/features/silent.prf:
valkyrie.pro:
qmake: FORCE
	@$(QMAKE) PREFIX=/usr/local -o Makefile valkyrie.pro

qmake_all: sub-src-qmake_all FORCE

make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-check:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /Users/prodesign/valkyrie/src/src.pro PREFIX=/usr/local -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

